### ISSUE TITLE
[KDE Plasma] Transparency works completely fine, however blur effect does not work.

### ISSUE THREAD

**Issue by Weetile** [manilarome/thunderblurred#2]
![image](https://user-images.githubusercontent.com/7700383/82123021-ffbdcb00-978e-11ea-9f8a-e64103d8b0b0.png)
I am using KDE Plasma on Manjaro Linux. While blur works under other transparent windows, it seems that it does not work under Thunderblur. 

I have Blur enabled in System Settings, are compositing effects not supported for KWin?

**Comment by Optimalgitit** [comment]
System Settings > Desktop Effects > Enable Blur

But this doesn't enable it for ALL applications.

For that, we need a KWin Script.

System Settings > KWin Scripts > Enable Force Blur

If force blue isn't installed, click Get New Scripts, search for Force Blur, install it and enable it.

**Comment by manilarome** [comment]
Follow @Optimalgitit instructions then go to preferences again and change the theme from default to dark.
