### ISSUE TITLE
Error with 'sh': Double bracket not found

### ISSUE THREAD

**Issue by Ilphrin** [manilarome/thunderblurred#4]
Hi!

If running the mentionned sh command to install, there is an error, because double brackets isn't POSIX and only bash can handle it, using bash instead of sh fixes the issue for me

`./install.sh: 50: [[: not found
[!!] No thunderbird user profile directory found. Make sure to run Thunderbird atleast once! Terminating...`

**Comment by manilarome** [comment]
Yep, the install script is not yet POSIX compliant. But yeah I should write in README that you need `bash` to run it. Thanks for the info!
